package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Children;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ChildrenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int insert(Children record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    Children selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    List<Children> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int updateByPrimaryKey(Children record);
}