package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.ActivitiesGroup;
import lt.vu.mybatis.model.ChildrenActivities;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ChildrenActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN_ACTIVITIES
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    int insert(ChildrenActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHILDREN_ACTIVITIES
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    List<ChildrenActivities> selectAll();


}