package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Teacher;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    int updateByPrimaryKey(Teacher record);
}