package lt.vu.mybatis.model;

public class ChildrenActivities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN_ACTIVITIES.CHILDRENLIST_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Integer childrenlistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN_ACTIVITIES.ACTIVITIES_GROUPS_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Integer activitiesGroupsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN_ACTIVITIES.CHILDRENLIST_ID
     *
     * @return the value of PUBLIC.CHILDREN_ACTIVITIES.CHILDRENLIST_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Integer getChildrenlistId() {
        return childrenlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN_ACTIVITIES.CHILDRENLIST_ID
     *
     * @param childrenlistId the value for PUBLIC.CHILDREN_ACTIVITIES.CHILDRENLIST_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setChildrenlistId(Integer childrenlistId) {
        this.childrenlistId = childrenlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN_ACTIVITIES.ACTIVITIES_GROUPS_ID
     *
     * @return the value of PUBLIC.CHILDREN_ACTIVITIES.ACTIVITIES_GROUPS_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Integer getActivitiesGroupsId() {
        return activitiesGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN_ACTIVITIES.ACTIVITIES_GROUPS_ID
     *
     * @param activitiesGroupsId the value for PUBLIC.CHILDREN_ACTIVITIES.ACTIVITIES_GROUPS_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setActivitiesGroupsId(Integer activitiesGroupsId) {
        this.activitiesGroupsId = activitiesGroupsId;
    }
}