package lt.vu.mybatis.model;

import java.util.Date;

public class Children {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.BIRTHDATE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.FIRST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.LAST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.PERSONAL_CODE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Long personalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHILDREN.KIND_GROUP_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    private Integer kindGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.ID
     *
     * @return the value of PUBLIC.CHILDREN.ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.ID
     *
     * @param id the value for PUBLIC.CHILDREN.ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.BIRTHDATE
     *
     * @return the value of PUBLIC.CHILDREN.BIRTHDATE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.BIRTHDATE
     *
     * @param birthdate the value for PUBLIC.CHILDREN.BIRTHDATE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.FIRST_NAME
     *
     * @return the value of PUBLIC.CHILDREN.FIRST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.CHILDREN.FIRST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.LAST_NAME
     *
     * @return the value of PUBLIC.CHILDREN.LAST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.LAST_NAME
     *
     * @param lastName the value for PUBLIC.CHILDREN.LAST_NAME
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.PERSONAL_CODE
     *
     * @return the value of PUBLIC.CHILDREN.PERSONAL_CODE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Long getPersonalCode() {
        return personalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.PERSONAL_CODE
     *
     * @param personalCode the value for PUBLIC.CHILDREN.PERSONAL_CODE
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setPersonalCode(Long personalCode) {
        this.personalCode = personalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHILDREN.KIND_GROUP_ID
     *
     * @return the value of PUBLIC.CHILDREN.KIND_GROUP_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public Integer getKindGroupId() {
        return kindGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHILDREN.KIND_GROUP_ID
     *
     * @param kindGroupId the value for PUBLIC.CHILDREN.KIND_GROUP_ID
     *
     * @mbg.generated Sat Apr 11 18:34:57 EEST 2020
     */
    public void setKindGroupId(Integer kindGroupId) {
        this.kindGroupId = kindGroupId;
    }


}