package lt.vu.mybatis.model;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEACHER.ID
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEACHER.FIRST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEACHER.LAST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEACHER.PERSONAL_CODE
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    private Long personalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEACHER.ID
     *
     * @return the value of PUBLIC.TEACHER.ID
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEACHER.ID
     *
     * @param id the value for PUBLIC.TEACHER.ID
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEACHER.FIRST_NAME
     *
     * @return the value of PUBLIC.TEACHER.FIRST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEACHER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.TEACHER.FIRST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEACHER.LAST_NAME
     *
     * @return the value of PUBLIC.TEACHER.LAST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEACHER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.TEACHER.LAST_NAME
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEACHER.PERSONAL_CODE
     *
     * @return the value of PUBLIC.TEACHER.PERSONAL_CODE
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public Long getPersonalCode() {
        return personalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEACHER.PERSONAL_CODE
     *
     * @param personalCode the value for PUBLIC.TEACHER.PERSONAL_CODE
     *
     * @mbg.generated Thu Apr 02 20:14:32 EEST 2020
     */
    public void setPersonalCode(Long personalCode) {
        this.personalCode = personalCode;
    }
}